typography_spectrum: 0.9056468995868938
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.2514544443139751
  lightness: 0.6052240095147402
  saturation: 0.11913864667389062
  rhythmicContrast: 0.5281157378073191
github: true
layout_spectrum: 0.9489652119872926
analytics:
  facebook: ''
  google: UA-107039528-1
  twitter: ''
author:
  name: Mark Vange
  url: 'https://icomafia.org'
  email: mvange@tokeniq.io
name: icomafia.org
navigation:
  - name: House Rules
    id: 8a067621-1932-4a19-b737-8e8d51c573f0
    type: content
  - name: The List
    id: 9963be28-5e98-40ec-94db-14be11388805
    type: content
title: ICO Mafia
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3e28fd2-0636-42c9-943d-5364da6efb61.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3e28fd2-0636-42c9-943d-5364da6efb61.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Private discussion group focused on improving the ICO industry
purpose:
  - type: external
    url: 'http://icomafia.org/rss.xml'
    label: Subscribe to RSS
